config/routes.rb
Lunker::Application.routes.draw do

  devise_for :admins

  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit_reg
  end

  devise_for :users, skip: [:sesssions],
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

   as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end


  resources :user_friendships do 
    member do
      put :accept
    end
  end
  
  resources :photos do
    resources :comments
  end

  
  resources :statuses  do
    resources :comments
  end

  resources :contest
  resources :tos

  get 'feed', to: "statuses#index", as: :feed
  get 'new', to: "statuses#new", as: :new
  root to: 'home_page#index'

  get '/:id', to: 'profiles#show', as: 'profile'
 












end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :authenticate_user!, only: [:show]
	
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@photos = Photo.where(:user_id => @user.id).page(params[:page]).per_page(20)
  		render action: :show
  	else	
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class= "span12">
	<h1>Member Profile</h1>
</div>
<div class= "span1">
      <%=  image_tag(@user.gravatar_url) %>
</div>
<div class= "span10">
<p>Profile name: <%= @user.profile_name %></p>
<p>Member Since: <%= @user.created_at.to_date %></p>
<p>Last Signed In: <%= @user.last_sign_in_at.to_date %></p>
</div>
<div class= "span2">
    <% if user_signed_in? %>
    	<% if current_user.id != @user.id %>  
    		<% if signed_in? %>
    			<div id="friend-status">
    				<% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
    					<%= link_to "Edit Friendship", edit_user_friendship_path(friend_id: @user), class: 'btn' %>
    				<% else %>
    					<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn', id:'add-friendship', data: {friend_id: @user.to_param} %>
    				<% end %>
    			</div>
    		<% end %>
    	<% end %>
    <% end %>
</div>
 
    <div class= "span12">
         <br/>  
         <br/>
        <% @photos.each do |photo| %>
            <div class = "span2">
                <div class = "thumb_image">
                    <div  class = "img-polaroid" ><%= link_to image_tag(photo.image_url(:thumb)), photo %></div>
                </div>
            </div>
        <% end %> 
    </div>                           
                