config/routes.rb
Lunker::Application.routes.draw do

  devise_for :admins

  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit_reg
  end

  devise_for :users, skip: [:sesssions],
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

   as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end


  resources :user_friendships do 
    member do
      put :accept
    end
  end
  
  resources :photos do
    resources :comments
  end

  
  resources :statuses  do
    resources :comments
  end

  resources :contest
  resources :tos

  get 'feed', to: "statuses#index", as: :feed
  get 'new', to: "statuses#new", as: :new
  root to: 'home_page#index'

  get '/:id', to: 'profiles#show', as: 'profile'
 












end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order("rank DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])
    @commentable = @status
    @comments = @commentable.comments
    @comment = Comment.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end

  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to feed_path, notice: 'Status was successfully created.' }
        format.json { render json: feed_path, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])

    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.input :content, label: "Topic" %>

  <div class="form-actions">
    <%= f.button :submit, 'Post It!' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
   <h3>Got something to say... Post it here</h3>

<%= link_to "Post a New Topic", new_path, class: "btn btn-success" %>
</br>
</br>
<% @statuses.each do |status| %>
<div class="status">
  <div class = "row">
    <div class= "span1">
      <%=  link_to image_tag(status.user.gravatar_url), profile_path(status.user) %>
    </div>
      <div class= "span11">
        <strong><%= status.user.profile_name %> says...</strong>
        <p><%=  link_to status.content, status_path(status), {:style=>'color:#002859;', :class => "css_class"} %></p>
          <div class="meta">
            <em><%= time_ago_in_words(status.created_at) + " ago" %></em>
            <% if current_user == status.user || current_user.try(:admin?) %>
              <span class= "admin">
                | <%= link_to 'Edit', edit_status_path(status) %> |
                <%= link_to 'Delete', status, confirm: 'Are you sure?', method: :delete %>
              </span>
            <% end %>
        </div>
     </div>
  </div>
</div>

<% end %>
</br>
<p style= "text-align: center;"><i class="icon-star-empty icon-spin icon-2x"></i></p>

<h2 style= "font-family: 'Patrick Hand SC', cursive; text-align: center;">Get an Avatar <%= link_to "HERE", "http://www.gravatar.com" %></h2>
</br>

app/views/statuses/new.html.erb
<h3>What do you have to say...</h3>

<%= render 'form' %>

<%= link_to 'Back', feed_path %>

app/views/statuses/show.html.erb
<div class="row">
	<br>
	<div class= "span1 offset1">
      <%=  link_to image_tag(@status.user.gravatar_url), profile_path(@status.user) %>
    </div>
     <div class= "span10">	
		<h3><%= @status.user.profile_name %> says...</h3></br>
	</div>
	<div class= "span10 offset1">
			
			<div class ="well">
				<div class= "status_align"><%= @status.content %></div>
			</div>
			

	</div>
	<div class= "span12">
		<% if user_signed_in? %>
				<% if current_user == @status.user || current_user.try(:admin?) %>
					<div class= "align">
					<%= link_to raw('<i class="icon-circle-arrow-left"></i> back'), statuses_path %> | 
					<%= link_to raw('<i class="icon-edit"></i> edit'), edit_status_path(@status) %> | 
					<%= link_to raw('<i class="icon-trash"></i> delete'), @status, confirm: 'Are you sure?', method: :delete %></div></br>
				<% end %> 
			<% end %>	
			
			<%= render "comments/comments" %>
		
		<div class= "status_comment">
			<%= render "comments/form" %>
		</div>
	</div>

	<div class="span4 offset5">
			<% if current_user.try(:admin?) %>
		
				<%= simple_form_for @status do |f| %>
					<%= f.input :rank %>
					<%= f.button :submit %>
				<% end %>

			<% end %>
		</div>
</div>