config/routes.rb
Lunker::Application.routes.draw do

  devise_for :admins

  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
    get '/edit', to: 'devise/registrations#edit', as: :edit_reg
  end

  devise_for :users, skip: [:sesssions],
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

   as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end


  resources :user_friendships do 
    member do
      put :accept
    end
  end
  
  resources :photos do
    resources :comments
  end

  
  resources :statuses  do
    resources :comments
  end

  resources :contest
  resources :tos

  get 'feed', to: "statuses#index", as: :feed
  get 'new', to: "statuses#new", as: :new
  root to: 'home_page#index'

  get '/:id', to: 'profiles#show', as: 'profile'
 












end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
<div class= "text-center">©2013 lun-ker</br>

<%= link_to "Terms of Service", tos_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>lun-ker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker|Nothing+You+Could+Do|Patrick+Hand+SC' rel='stylesheet' type='text/css'>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40433526-1', 'lun-ker.com');
  ga('send', 'pageview');

  </script>
</head>

<body>

  <div class="banner">
    <%=image_tag("banner.png", alt: "banner")%>
  </div>

	<div class="navbar" data-spy="affix" data-offset-top="70">
  	<div class="navbar-inner">
        <div class = "container">
      			<ul class="nav">
                <li><%= link_to raw('<i class="icon-home icon-large"></i> Home'), root_path %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to raw('<i class="icon-camera-retro icon-large"></i> Photos'), photos_path %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to raw('<i class="icon-comments-alt icon-large"></i> Forum'), statuses_path %></li>
                <li class="divider-vertical"></li>
                <li><%= link_to raw('<i class="icon-money icon-large"></i> Contests'), contest_index_path %></li>
    			 	</ul>

            <ul class="nav pull-right">
                <% if user_signed_in? %>
                  <li><%= link_to raw('<i class="icon-user icon-large"></i> Friends'), user_friendships_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to current_user.profile_name, edit_reg_path %></li>
                  <li class="divider-vertical"></li>
                  <li><%= link_to "Log Out", logout_path %></li>
                <% else %>
                  <li><%= link_to "Register",register_path %></li>
                  <li><%= link_to "Log In",login_path %></li>
                <% end %>
            </ul>

  		  </div>
  	 </div>
  </div>

  <div class = "container">
    <% flash.each do |type, message| %>
      <div class= "alert <%= flash_class type %>">
          <button class="close" data-dismiss="alert"></button>
          <%= message %>
      </div>
    <% end %>


    <%= yield %>
  </div>

    <%= render 'layouts/footer' %>

</body>
</html>